version: '3'

services:
    app:
        container_name: vue_crash
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 8888:8080
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        networks:
            - localnet

volumes:
    node_modules:
    web-root:
        driver: local
networks:
    localnet:
        driver: 'bridge'