FROM node:lts-alpine
LABEL maintainer="Lykourgos Tsirikos <lykourgos.tsirikos@gmail.com>"

# set working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./
RUN npm install --silent

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
# RUN npm run build

EXPOSE 8080
# start app
CMD ["npm", "run", "serve"]